platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaliad/project-monitor

inputs:
  - name: project-monitor-repo

run:
  path: project-monitor-repo/concourse/scripts/run-tests.sh
